### ISSUE TITLE
Add `getContainer` to EncoderInterface

### ISSUE THREAD

**Issue by lindyhopchris** [neomerx/json-api#76] opened 2015-09-13 18:39 UTC
At the moment you can do `getEncoderOptions` but you can't do `getContainer` to get the schemas from an encoder. If your encoder has been created by your service container in your framework, there's no way to get at the schemas to work out the location header for a created response.

Solution - add `getContainer` to the `EncoderInterface`. Alternative names for the method would be `getSchemasContainer` or `getSchemas`.

I'm happy to add if you want me to do it. As it's a single commit, could go straight into the develop branch? Or would you want it as a pull request?

**Comment by neomerx** [comment] 2015-09-14 11:09
I find it unnatural to get it from encoder interface. Container is internal specifics of of encoder and it should be hidden from outside world IMO.
I had similar problem with `Location` header in limoncello and solved it [here](https://github.com/neomerx/limoncello/blob/master/src/Http/JsonApiTrait.php#L413-L427). Basically with passing `Factory` to `Encoder` it uses the factory to create one more `Container` (it's lightweight class) and creates provider for that 1 class (lightweight as well).
If you can find elegant solution for that I would be happy to have it in code.

**Comment by lindyhopchris** [comment] 2015-09-14 11:38
The only reason it works there is because you are loading and setting config on the controller that includes the schema. This to me is unnatural - the codec matcher is a service, so I'm providing it to the controller from the service container. So the thing that constructs the create response needs to get the schemas from the encoder that it has access to. 

(Note that the thing that constructs the response may not be the controller itself - in Zend 2 it is an event listener that listens to the model returned by the controller.)

I'm providing codec matchers from the service provider because for a consistent API, the codec matcher is consistent across multiple controllers (route groups in Laravel terms). It's the encoder that has knowledge of schemas, not the controller - so it makes sense to be able to get the schemas from the encoder.

It seems a bit unnecessary to not provide public access to the schemas within the encoder... as this package is framework-agnostic, there's going to be different approaches to tying it into different frameworks. I don't think it's solely an internal concern... effectively the encoder holds the state of the view that is going to be returned to the client. Why give access to the encoder options but not the schemas?

The only alternative solution I can think of is to provide a method on the EncoderInterface that is able to get the the URI for the resource - considering that it is a construct of both the url prefix in the encoder options and the url sub link in the relevant schema. The only thing that has access to both is the Encoder.

**Comment by neomerx** [comment] 2015-09-15 10:44
@lindyhopchris Sorry for a little delay in reply I was focused on #74 

With adding polymorphic support (huge and complex enhancement btw) I've changed underlying `Encoder` new instance creation which hopefully should make you totally happy.

``` php
public static function instance(array $schemas, EncoderOptions $encodeOptions = null)
{
    // FactoryInterface will probably be in your DI container
    $factory   = static::getFactory();
    // ContainerInterface will probably be in your DI container
    $container = $factory->createContainer($schemas);
    // Encoder now accepts Container as input param
    $encoder   = $factory->createEncoder($container, $encodeOptions);

    return $encoder;
}
```

**Comment by neomerx** [comment] 2015-09-15 10:48
@lindyhopchris I've got a test error that [occurs only on 5.5](https://travis-ci.org/neomerx/json-api) Have you got an ability to test it on 5.5?

**Comment by lindyhopchris** [comment] 2015-09-15 11:58
@neomerx I can test on 5.5 at home (I'm on 5.6 at work). Will have a look tonight.

I'm not convinced that change will help. I've got multiple schemas because there's multiple APIs in the application. The schemas are separated because for security reasons you don't want one API encoding by accident objects that it should never be encoding. My solution is to have a different Codec Matcher for each API, within which the encoders hold the schemas for that specific API. By having different codec matchers, I can support different media types on each API depending on the intended clients of the separated APIs.

Also if you're going to take that approach, you need to provide a static `Encoder::setFactory($factory)` method to allow the factory that is used in `static::instance()` to be overridden.

Also your supplied `Container` class does not allow setting schemas after creation. So even if my DI container returned a Container instance, I wouldn't be able to set the schemas on it.

Also you need to change the input `array $schemas` so that it can take an instance of `ContainerInterface`, or an array.

The whole reason I'm trying to avoid extending tonnes of your classes is because to supply my Laravel and Zend 2 integrations as packages that can be used in multiple applications, I'm going to have to extend your interfaces as well and check for instances of my extended interfaces. That of course can be done but starts to get messy...

**Comment by lindyhopchris** [comment] 2015-09-15 18:54
@neomerx just went to test that 5.5 error, but looks like you've already fixed it.

**Comment by neomerx** [comment] 2015-09-15 18:54
@lindyhopchris It looks it was a problem on Travis's side. It works now.

**Comment by neomerx** [comment] 2015-09-15 19:31
As this change is possible after #74 (hopefully tomorrow) we have time :smile: Please don't consider it as saying 'no'. If that's the only or best possible solution we'll do it. For now it's just a discussion.

I'm not an expert in ZF so forgive me if I'm wrong. 

> I've got multiple schemas because there's multiple APIs in the application. The schemas are separated because for security reasons ...

I assume you have 1 set of schemas for **request** which is selected based on current user, API endpoint, etc. As PHP throws away everything after **request** is handled it shouldn't be a problem to have `ContainerInterface` in DI.
So instead of taking `ContainerInterface` from encoder you can create encoder with your `ContainerInterface` and use if for any other purposes before or after `Encoder` creation.

> Also if you're going to take that approach, you need to provide a static Encoder::setFactory($factory) method to allow the factory that is used in static::instance() to be overridden.

`Encoder::instance` is just a short way to create encoder when no modifications/extensions to it applied. It's an equivalent to

``` php
    $schemas = ...;
    $encodeOptions = ...;

    $factory   = new Factory();
    $container = $factory->createContainer($schemas);
    $encoder   = $factory->createEncoder($container, $encodeOptions);
```

So no `Encoder::setFactory` is not required. When the package is modified (99% changes go through Factory) and if keeping `Encoder::instance` semantics is desired method `Encoder::getFactory()` should be overriden (1 line `return new CustomFactory();`).

> Also your supplied Container class does not allow setting schemas after creation. So even if my DI container returned a Container instance, I wouldn't be able to set the schemas on it.

In Laravel you can do something like (just the idea not real code)

``` php
$isSingleton = false;
app()->container->bind(ContainerInterface::class, $isSingleton, function () {
    $factory   = app()->container->get(FactoryInterface::class);
    $schemas   = getSchemasForCurrentUserAndRequest();
    $container = $factory->createContainer($schemas);

    return $container;
});
```

The closure could be called only once or on every call depending from `$isSingleton`. I guess ZF can do something similar. So you can change container (or just re-bind if necessary with new schemas).

> The whole reason I'm trying to avoid extending tonnes of your classes is because ...

I think you won't need to extend my classes at all. I think we are talking only about changing `Encoder::instance` (1 line) with more flexible `Factory` based way (+2 lines).

**Comment by lindyhopchris** [comment] 2015-09-15 20:39
Yep, that I all know. The thing is I've been doing one codec matcher per request. So that's what's sitting in my DI container, and I've been wanting to get the schemas from the matched encoder.

I suppose I can refactor my code to hold schemas separately. It just seems like a lot of work when the thing that needs access to the schemas already has access to an encoder, which in turn is always going to have knowledge of the schemas!

**Comment by lindyhopchris** [comment] 2015-09-16 08:12
@neomerx Have refactored my code. The `createContainer` and `createEncoder` will work. I still think you should be allowed to get schemas from an encoder, because an encoder is always going to have schemas, but if you're against adding it into the interface then my changes will work around it.

**Comment by lindyhopchris** [comment] 2015-09-16 10:07
@neomerx What's `$inclusionResourceType` on `ParametersParserInterface::parse()`?

If this is a resource type, then this breaks parsing headers + parameters before arriving in the controller action method. The JSON API spec says that include paths should come in on the `include` query parameter, so there shouldn't be any need to provide a resource type to parse parameters into a `ParametersInterface` object. If encoding needs to know the resource type that the include paths relate to, then this should be defined later as it is an encoding (view layer) concern, not a parameter parsing (request - MVC event or middleware) concern.

**Comment by neomerx** [comment] 2015-09-16 11:41
@lindyhopchris As a reply to your critics on 'Encoder::getEncoderOptions` I've removed it :wink:

As for `$inclusionResourceType` I probably need a better name. This is a JSON API type for included paths from `$request`. The problem is that spec do not allow specify include paths per type but only a list of paths for some default type. In most cases it's fine as we work with single type resources. However for polymorphic resources it creates ambiguity. Should include paths be applied to all polymorphic resources or just for type of the first one or ...?

I've added to encoder support for multi-type include paths parameter so it can work with many type => paths mappings. It used to be just an array

``` php
['some.path', 'one.more.path', ...]
```

but now json api type should be specified

``` php
[
   'people' => ['posts', 'posts.comments', ...],
   'sites'  => ['...', ...],
]
```

Thus we get include paths from request parameters without json api type (as spec requires) however when parameters are passed to encoder the json api type should be specified. That's what `$inclusionResourceType` is.

**Comment by neomerx** [comment] 2015-09-16 11:55
I think `$inclusionResourceType` should be optional and required only if include paths are specified in request.

**Comment by lindyhopchris** [comment] 2015-09-16 12:02
@neomerx will message you via Gitter.

**Comment by neomerx** [comment] 2015-09-23 00:51
merged to master

**Closed as completed by neomerx** 2015-09-23 00:51 UTC
Labels: question
