### ISSUE TITLE
Schema is not registered for a resource at path ''

### ISSUE THREAD

**Issue by thiagoreri** [neomerx/json-api#209] opened 2018-04-13 23:49 UTC
I'm using this library and the following error is occurring in the title

**Comment by neomerx** [comment] 2018-04-15 01:33
You are likely trying to encode a resource without a Schema for it. Which one? See the `path` value as a hint.

**Comment by bravo-kernel** [comment] 2018-04-15 05:28
@neomerx I think this can be closed as it was solved here https://github.com/FriendsOfCake/crud-json-api/issues/37#comment-381347327

**Comment by neomerx** [comment] 2018-04-15 08:55
@bravo-kernel Thanks. Can the message be improved to make it clearer about the underlying issue cause?

**Comment by bravo-kernel** [comment] 2018-04-15 09:04
I was thinking exactly the same as this seems to be the only (and recurring problem) for our users. Unsure how but.. on our list.

**Comment by neomerx** [comment] 2018-04-15 09:07
You can use included exception with the cause of the error.

![image](https://user-images.githubusercontent.com/10420662/38776784-7d4dc3ba-40a5-11e8-8252-b57638095265.png)

**Comment by bravo-kernel** [comment] 2018-04-15 10:08
🥄 much appreciated, I will see if I can provide a more descriptive message (pointing to CakePHP)

**Comment by neomerx** [comment] 2018-04-15 10:46
I've modified the error message.

Now for an unknown resource of type `Neomerx\Tests\JsonApi\Data\Author`, the error message would be
> Getting Schema for a top-level resource of type `Neomerx\Tests\JsonApi\Data\Author` failed. Please check you have added a Schema for this type.

and for a resource in a relationship, the message would be
> Getting Schema for a resource of type `Neomerx\Tests\JsonApi\Data\Author` at path `comments.author` failed. Please check you have added a Schema for this type.

**Closed as completed** 2018-04-15 10:49 UTC
Labels: enhancement, question

**Comment by bravo-kernel** [comment] 2018-04-15 10:50
👍 

I did understand correctly that we can override the message yes? In our case the schema is (almost always) dynamic and retrieved from Table and Entity. I would like to point Cake users directly to those files.

**Comment by neomerx** [comment] 2018-04-15 10:56
Yes, the library is highly modular and you can [replace any part of the library with your own implementation](`Neomerx\Tests\JsonApi\Data\Author`).

I think you would need to replace `\Neomerx\JsonApi\Factories\Factory::createParser` with your own messages. The link above has an overview of the process and `tests` have a couple of samples how to do that.

UPD: see `tests/Extensions/Issue49` as a sample how to replace this method

**Comment by neomerx** [comment] 2018-04-15 11:08
@bravo-kernel You might need some changes from my side e.g. make `\Neomerx\JsonApi\Encoder\Parser\Parser::getSchema` protected instead of private. Feel free to experiment with the code and let me know if any help needed.

**Comment by neomerx** [comment] 2018-04-15 11:10
The changes released in 2.0.5

**Comment by bravo-kernel** [comment] 2018-04-15 11:28
OK, thanks.
