### ISSUE TITLE
Errors as a Schema

### ISSUE THREAD

**Issue by designermonkey** [neomerx/json-api#206] opened 2018-03-23 20:07 UTC
Wouldn't it be great if you could register an object type and have it's Schema be the Error class? Or better yet, have another BaseSchema type that is ErrorSchema?

I find it weird that most of the codebase is automatic to some degree, yet we have to manually create Error instances. Our code base uses a specific class to pass errors up to the presentation layer, and I am having to manually convert them to Error instances to be encoded.

**Comment by neomerx** [comment] 2018-03-24 09:00
How do you see using such feature? Can you please post a hypothetical code sample?

**Comment by lindyhopchris** [comment] 2018-03-24 10:42
I find errors being created from within the stack strange too, because it creates the problem of how to issue an `id` for the error? Generally an error down in the stack doesn't know if an id should be allocated to the error, or even if it does, how that id should be generated. Is the ID a database reference, a log reference, etc etc? It makes sense to do this further up the stack because you probably only need to allocate an id if the errors are definitely going to be sent back to the client. We have production apps doing this, but they effectively have to loop over all the errors and re-create them with IDs before returning them to the client.

The other main case here is how to convert exceptions to errors. The problem is a lot of the time you're handling exceptions that come from the framework you're operating in, which obviously don't have any knowledge of JSON API and don't have any JSON API errors attached to them. You need some sort of way to know how to convert a specific exception into JSON API errors. At the moment I deal with this using an `ExceptionParserInterface`, but it isn't pretty!

@designermonkey suggestions sounds good, though I wouldn't want to mix resource schemas with error schemas. It's almost like you need some sort of schema specific for mapping objects to errors, with an object either mapping to one or many errors (because an object could actually need multiple JSON API errors e.g. if it is a validation Exception that has multiple validation messages for different source pointers in the JSON API structure).

It would be important that any such feature allows you to map parent classes to schemas because a lot of frameworks will extend exceptions. E.g. a Symfony HTTP exception is extended by lots of other exceptions, so you'd probably want to register one error schema for every Symfony HTTP exception.

Some sort of error schema would also allow you to inject that schema with whatever service you use to issue IDs for your error objects. It would help if `Error` had a `setId` method on it.

**Comment by designermonkey** [comment] 2018-03-24 12:10
We use the notification pattern to collect together any exceptions from further down the chain so have a consistent class type being given back for presentation, so I was expecting it to just work the same way a normal schema would, but with functions to fill in details fo the error class instead.

**Comment by neomerx** [comment] 2018-03-24 12:37
@designermonkey I still would like to have a look at how you see usage should look like leaving implementation details aside.

Meantime, short demo on how to convert exceptions to errors
```php
    public function testEncodeExceptions(): void
    {
        // or errors or whatever representing error info
        $inputExceptions = [
            new \Exception('one'),
            new \Exception('two'),
            new \Exception('three?'),
            new \Exception('dunno'),
        ];

        $converter = function (iterable $exceptions): iterable {
            // sorry about formatting I want to have short code for this boilerplate stuff
            $tmpError = new class extends stdClass implements ErrorInterface
            {
                public function __construct()
                {
                    $this->id = $this->links = $this->status
                        = $this->code = $this->title = $this->detail
                        = $this->sourse = $this->meta = null;
                }

                public function getId() {return $this->id;}
                public function getLinks(): ?array {return $this->links;}
                public function getStatus(): ?string {return $this->status;}
                public function getCode(): ?string {return $this->code;}
                public function getTitle(): ?string {return $this->title;}
                public function getDetail(): ?string {return $this->detail;}
                public function getSource(): ?array {return $this->sourse;}
                public function getMeta() {return $this->meta;}
            };

            foreach ($exceptions as $exception) {
                /** @var \Exception $exception */
                $tmpError->title = 'oops';
                $tmpError->detail = $exception->getMessage();

                // well, you know better how to deal with your exceptions...

                yield $tmpError;
            }
        };

        $actual = Encoder::instance()->encodeErrors($converter($inputExceptions));
        $expected = <<<EOL
        {
           "errors":[
              {
                 "title":"oops",
                 "detail":"one"
              },
              {
                 "title":"oops",
                 "detail":"two"
              },
              {
                 "title":"oops",
                 "detail":"three?"
              },
              {
                 "title":"oops",
                 "detail":"dunno"
              }
           ]
        }
EOL;
        // remove formatting from 'expected'
        $expected = json_encode(json_decode($expected));

        $this->assertEquals($expected, $actual);
    }
```

**Comment by neomerx** [comment] 2018-03-27 17:45
Guys, I can add `setXXX` methods to `Error` and the conversion example will boil down to this

```php
        $converter = function (iterable $exceptions): iterable {
            $tmpError = new Error();
            foreach ($exceptions as $exception) {
                $this->copyExceptionToJsonApiError($exception, $tmpError);
                yield $tmpError;
            }
        };

        $result = Encoder::instance()->encodeErrors($converter($inputExceptions));
```

I think `copyExceptionToJsonApiError` (or `copyAppErrorToJsonApiError`, or ``copyValidationErrorsToJsonApiError``) is very application specific and unlikely to have any common part.

If you have any ideas/requirements please share within a reasonable time period. Otherwise, changes will be limited to adding `setXXX` methods to `Error`.

**Comment by lindyhopchris** [comment] 2018-03-28 08:20
Setters on the error object would definitely help.

**Comment by neomerx** [comment] 2018-03-29 09:39
The setters added to `develop`. Unless new ideas/requirements appear the changes will be merged to `master` and released on Friday.

**Closed as completed** 2018-03-30 20:01 UTC
Labels: enhancement, question

**Comment by neomerx** [comment] 2018-03-30 20:07
[released](https://github.com/neomerx/json-api/releases/tag/v2.0.4)

**Comment by ghost** [comment] 2018-10-09 10:45
Sorry to have left this so long to come back to.

What I am hoping to achieve is something like the following:

```php
$instance = Encoder::instance([
    MyError::class => MyErrorSchema::class,
]);

$errors = [new MyError(...)];

$output = $instance->encodeData($errors);
```

MyError is not a neomerx class, and a schema shows how to convert it to a neomerx error object. I don't want to have to anything inside my implementation as I think as the encoder can handle everything else for all other schemas, why doesn't it for errors?

If a set of data is provided to the encoder that has mixed objects in it, and an error is present, the rest of the data should be ignored, and the error only should be encoded.

I know this changes the interface somewhat, but I think it would make the library more user friendly.

**Comment by neomerx** [comment] 2018-10-09 13:47
JSON API [Data](http://jsonapi.org/format/#document-top-level) and [Errors](http://jsonapi.org/format/#errors) do not have much in common.
- `data` has `type` and `id` unlike `error` has only `id`
- `data` has things like `relationships`, `included`, `links`, a few `metas` and others that `errors` don't
- for `data` oprations like `create`, `update` and `delete` make sense but for errors don't

IMHO they are too different to look at them as `same thing`.

As for mixing `data` with `errors`. Is it a common scenario? Like reading data from database where some rows are ok and have some error instead of some of them? I just don't see such mix as a common thing.

But OK, let's assume we have it. A list of 'normal' object mixed with 'errors/exceptions'. How it should be handled? Iterate through all of them, if an object with 'special error schema' found then forget all and iterate further encoding only errors? Have special schemas for errors?

If I understand you correctly, the following method would make what you want

```php
function encode($data): string
{
    // create encoder
    $encoder = ...;

    if (is_iterable($data) === false) {
        // check if data is error and call either method for data or for errors

        $result = ...;
    } else {
        $errors = null;
        $resources = [];

        // iterate through data and split it into resources and errors
        // remember both as input data might be iterator and we can't read it again

        if ($errors === null) {
            // encode as data
            $result = ...;
        } else {
            // encode as errors
            $result = ...;
        }
    }

    return $result;
}
```

**Comment by ghost** [comment] 2018-10-09 18:00
I can see your point. What I want to avoid is having to have knowledge of objects in the neomerx implementation other than the encoder instance I pass into my application. Currently, I can pass anything in as data to `encodeData` as long as I have defined a schema for it, yet I have to have made `ErrorInterface` instances which may also need to know about `LinkInterface` instances too, which I then pass in to `encodeErrors`. There's a coupling here that should be avoided; I _should_ be able to pass anything in to `encodeErrors` as with `encodeData`.

You're right that they probably should be different methods still, but we should be able to define a schema somewhere so that it's the neomerx encoder instance that does the heavy lifting of encoding our own error objects, not neomerx's. Is that making sense?

I guess you can ignore the part of me asking to do it all together, it is actually not the right way to do it, but thanks for the pseudo code anyway.

Maybe the schemas array could look for a schema keyed as simply `error` that follows an `ErrorSchema` interface for example?

**Comment by neomerx** [comment] 2018-10-09 18:18
> I want to avoid is having to have knowledge of objects in the neomerx implementation other than the encoder instance I pass into my application.

The best way is to have a class (+optional interface) that does exactly it

```php
class MyEncoder implements MyEncoderInterface {
    public function encode($data): string {
        // can handle resources/errors/...
        ...;
    }
}

// usage

function mySomeMethod(MyEncoderInterface $trueEncoder) {
    // bonus: you can mock MyEncoderInterface in tests
}
```

**Update**

I've given an example above how to convert Exceptions to Errors. So you don't need to pass anything from `Neomerx/*` namespace(s) to the method.

Copied from above
```php
        $converter = function (iterable $exceptions): iterable {
            $tmpError = new Error();
            foreach ($exceptions as $exception) {
                $this->copyExceptionToJsonApiError($exception, $tmpError);
                yield $tmpError;
            }
        };

        $result = Encoder::instance()->encodeErrors($converter($inputExceptions));
```

Using this approach you can completely decouple your code from mine.
